
<font size = 4 color='Orange'>
Learning Goals</font>

<font color = 'Orange' size = 3 >In this Exercise your goal is to make a good solution for the active competition on kaggle: https://www.kaggle.com/c/nlp-getting-started/data

<font color = 'Orange' size = 3 > In order to download the Datasets you will need to join and accept the terms and conditions of the competition. </font>

You need to report the parameters for the best three models into a table that will contain the model architecture and F1 score.
</font>

<font color = 'Blue' size = 4 > Structure of the Dataset </font>

<font color = 'Orange' size = 3>
The Dataset it's divided on two parts for training and testing. For the testing part you need to map the id's with the sample_submission.csv, where the target column is located.</li>
</font>

<font color = 'Blue' size = 4 >FIRST PART</font>

<font color = 'Orange' size = 3 > Choose a model that you will use from the pretrained BERT, RoBERTa, XLNet, XLM ... models for Text Classification [Hugging Face](https://huggingface.co/transformers/quicktour.html). 

Report the following parameters for models based on Transformers</font>
<ul>
<font color='orange'>
<li> Pretrained model</li>

<li>Loss function</li>
<li>Optimizer function for compiling</li>
<li>F1 score for the prediction of the test part (this is the metric for rating the models)
</li>
</ul>
<font color = 'Blue' size = 4 >SECOND PART</font>
<ul>
<font color='Orange'>
Cluster the tweets based on their embeddings using one of the clustering algorithms:

<li>K-Means Clustering</li>
<li>Agglomerative Clustering</li> 
<li>Affinity propagation Clustering</li> 
<li>Spectral Clustering</li> 
<li>DBSCAN Clustering</li>

</ul>

</font>

#Obtaining the Dataset

In [52]:
import pandas as pd

In [53]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [54]:
train=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/dataset lab 5/train.csv")
test=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/dataset lab 5/test.csv")
submission=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/dataset lab 5/sample_submission.csv")

In [55]:
train

id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this #earthquake M...       1  
1                Forest fire near La Ronge Sask. Canada       1  
2     All residents asked to 'shelter in place' are ...       1  
3     13,000 people receive #wildfires evacuation or...       1  
4     Just got sent this photo from Ruby #Alaska as ...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1  

[7613 rows x 5 columns]

In [56]:
test

id keyword location  \
0         0     NaN      NaN   
1         2     NaN      NaN   
2         3     NaN      NaN   
3         9     NaN      NaN   
4        11     NaN      NaN   
...     ...     ...      ...   
3258  10861     NaN      NaN   
3259  10865     NaN      NaN   
3260  10868     NaN      NaN   
3261  10874     NaN      NaN   
3262  10875     NaN      NaN   

                                                   text  
0                    Just happened a terrible car crash  
1     Heard about #earthquake is different cities, s...  
2     there is a forest fire at spot pond, geese are...  
3              Apocalypse lighting. #Spokane #wildfires  
4         Typhoon Soudelor kills 28 in China and Taiwan  
...                                                 ...  
3258  EARTHQUAKE SAFETY LOS ANGELES ‰ÛÒ SAFETY FASTE...  
3259  Storm in RI worse than last hurricane. My city...  
3260  Green Line derailment in Chicago http://t.co/U...  
3261  MEG issues Hazardous Weather Outlook (HWO) htt...  
3262  #CityofCalgary has activated its Municipal Eme...  

[3263 rows x 4 columns]

In [57]:
submission

id  target
0         0       0
1         2       0
2         3       0
3         9       0
4        11       0
...     ...     ...
3258  10861       0
3259  10865       0
3260  10868       0
3261  10874       0
3262  10875       0

[3263 rows x 2 columns]

In [58]:
print(train.shape)
print(test.shape)
print(submission.shape)

(7613, 5)
(3263, 4)
(3263, 2)


In [59]:
train.isna().sum()

id             0
keyword       61
location    2533
text           0
target         0
dtype: int64

In [60]:
test.isna().sum()

id             0
keyword       26
location    1105
text           0
dtype: int64

In [61]:
submission.isna().sum()

id        0
target    0
dtype: int64

In [62]:
train['target'].value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [63]:
submission['target'].value_counts()

0    3263
Name: target, dtype: int64

vo sample_submission.csv site vrednosti za target kolonata se 0. 

## prepearing data

In [64]:
train.columns

Index(['id', 'keyword', 'location', 'text', 'target'], dtype='object')

In [65]:
train.shape

(7613, 5)

In [66]:
test.columns

Index(['id', 'keyword', 'location', 'text'], dtype='object')

In [67]:
test.shape

(3263, 4)

# Tokenization

In [68]:
! pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [69]:
import transformers

In [70]:
# tokenizer = BertTokenizer.from_pretrained('bert-large-uncased', do_lower_case=True)

In [71]:
tokenizer = transformers.AutoTokenizer.from_pretrained('cardiffnlp/twitter-roberta-base-sentiment-latest')

Could not locate the tokenizer configuration file, will try to use the model config instead.
loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--cardiffnlp--twitter-roberta-base-sentiment-latest/snapshots/f8f82141e1c60fb0869fc353c1e84a944d4f920c/config.json
Model config RobertaConfig {
  "_name_or_path": "cardiffnlp/twitter-roberta-base-sentiment-latest",
  "architectures": [
    "RobertaForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "negative",
    "1": "neutral",
    "2": "positive"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "negative": 0,
    "neutral": 1,
    "positive": 2
  },
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attent

#### finding max_lenght

In [72]:
tokenized_train_temp = tokenizer(train.append(test)['text'].tolist(), max_length=10000, 
                         truncation=True, padding=True, 
                         add_special_tokens=True, return_tensors='np')

In [73]:
tokenized_train_temp

{'input_ids': array([[    0,  2522,   926, ...,     1,     1,     1],
       [    0, 42542,   668, ...,     1,     1,     1],
       [    0,  3684,  1196, ...,     1,     1,     1],
       ...,
       [    0, 19247,  5562, ...,     1,     1,     1],
       [    0,   448,  7170, ...,     1,     1,     1],
       [    0, 10431, 15075, ...,     1,     1,     1]]), 'attention_mask': array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])}

In [74]:
tokenized_train_temp["input_ids"]

array([[    0,  2522,   926, ...,     1,     1,     1],
       [    0, 42542,   668, ...,     1,     1,     1],
       [    0,  3684,  1196, ...,     1,     1,     1],
       ...,
       [    0, 19247,  5562, ...,     1,     1,     1],
       [    0,   448,  7170, ...,     1,     1,     1],
       [    0, 10431, 15075, ...,     1,     1,     1]])

In [75]:
print(len(tokenized_train_temp["input_ids"][0]))
print(len(tokenized_train_temp["input_ids"][125]))
print(len(tokenized_train_temp["input_ids"][-10]))

85
85
85


In [76]:
text_vector_len=len(tokenized_train_temp["input_ids"][0])

## Tokenization train

In [77]:
tokenized_train = tokenizer(train['text'].tolist(), max_length=text_vector_len, 
                         truncation=True, padding='max_length', 
                         add_special_tokens=True, return_tensors='np')

In [78]:
tokenized_train

{'input_ids': array([[    0,  2522,   926, ...,     1,     1,     1],
       [    0, 42542,   668, ...,     1,     1,     1],
       [    0,  3684,  1196, ...,     1,     1,     1],
       ...,
       [    0,   448,   134, ...,     1,     1,     1],
       [    0,  9497,  3219, ...,     1,     1,     1],
       [    0,   133,  9385, ...,     1,     1,     1]]), 'attention_mask': array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])}

In [79]:
train_input_ids=tokenized_train["input_ids"]
train_attention_mask=tokenized_train["attention_mask"]

In [80]:
train_input_ids[3]

array([    0,  1558,     6,   151,    82,  1325,   849, 29633, 23668,
        9750,  3365,    11,   886,  1437,     2,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1])

In [81]:
train_attention_mask

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])

In [82]:
y_train = train['target'].values

## Tokenization test

In [83]:
tokenized_test = tokenizer(test['text'].tolist(), max_length=text_vector_len, 
                         truncation=True, padding='max_length', 
                         add_special_tokens=True, return_tensors='np')

In [84]:
test_input_ids=tokenized_test["input_ids"]
test_attention_mask=tokenized_test["attention_mask"]

In [85]:
tokenized_test["input_ids"][-3]

array([    0, 19247,  5562, 17991,  1757,    11,  1568,  2054,   640,
          90,     4,   876,    73, 41967,   428, 35826,   438,  5383,
         257,   975,     2,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1,     1,     1,     1,     1,     1,
           1,     1,     1,     1])

# Creating train and validation dataset

In [86]:
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [87]:
from datasets import Dataset

In [88]:
dic = { "input_ids" : train_input_ids, "attention_mask" : train_attention_mask, "label": y_train}

In [89]:
data_set=Dataset.from_dict(dic)

In [90]:
data_set=data_set.train_test_split(test_size=0.2)

In [91]:
data_set

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'label'],
        num_rows: 6090
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'label'],
        num_rows: 1523
    })
})

In [92]:
test_data_dict={"input_ids" : test_input_ids, "attention_mask" : test_attention_mask}

In [93]:
test_dataset=Dataset.from_dict(test_data_dict)

# Building and training the model

In [94]:
# from transformers import BertForSequenceClassification
from transformers import DataCollatorWithPadding
from transformers import AutoModelForSequenceClassification,TrainingArguments,Trainer

In [95]:
training_args = TrainingArguments("test-trainer")

PyTorch: setting up devices
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).


In [96]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [97]:
model = AutoModelForSequenceClassification.from_pretrained("cardiffnlp/twitter-roberta-base-sentiment-latest", num_labels=2,ignore_mismatched_sizes=True)

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--cardiffnlp--twitter-roberta-base-sentiment-latest/snapshots/f8f82141e1c60fb0869fc353c1e84a944d4f920c/config.json
Model config RobertaConfig {
  "_name_or_path": "cardiffnlp/twitter-roberta-base-sentiment-latest",
  "architectures": [
    "RobertaForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.26.0",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 50265
}

loading weig

KeyboardInterrupt: ignored

In [ ]:
trainer = Trainer(
    model,
    training_args,
    train_dataset=data_set["train"],
    eval_dataset=data_set["test"],
    data_collator=data_collator,
    tokenizer=tokenizer,
)

In [ ]:
trainer.train()

# Prediction and evaluation

In [ ]:
import numpy as np

In [ ]:
predictions=trainer.predict(test_dataset)

In [ ]:
preds = np.argmax(predictions.predictions, axis=-1)

In [ ]:
preds

In [ ]:
submission["target"]=preds

In [ ]:
submission.to_csv("/content/drive/MyDrive/Colab Notebooks/dataset/dataset lab 5/submission.csv",index=False)

Score: 0.82745

#Clustering

In [ ]:
from sklearn.cluster import KMeans, AgglomerativeClustering, AffinityPropagation, SpectralClustering, DBSCAN
from sklearn import metrics


In [ ]:
combined_dataset=np.concatenate((train_input_ids,test_input_ids))

In [ ]:
combined_dataset.shape

In [ ]:
km = KMeans(n_clusters=10)
km.fit(combined_dataset)

clusters_km = km.labels_.tolist()

In [ ]:
ac=AgglomerativeClustering()
ac.fit(combined_dataset)

clusters_ac=ac.labels_.tolist()

In [ ]:
combined_df=train.append(test)

In [ ]:
dictionary={"text": combined_df['text'], "km_label": clusters_km, "ac_label": clusters_ac}

In [ ]:
combined_df=pd.DataFrame(data=dictionary)

In [ ]:
combined_df.groupby("km_label").size()

In [ ]:
combined_df.groupby("ac_label").size()

In [ ]:
combined_df.groupby(["km_label","ac_label"]).size()
